input_videos_folder_path: "/home/ariel/Downloads/"


videos:
  # video number 1
  - name: "VID_20190530_081812.mp4"
    start_frame: 0
    end_frame: 20


  # video number 2
  - name: "VID_20190530_081812.mp4"
    start_frame: 0
    end_frame:  # if no end_frame is specified the blurring will run until its ending


output_folder_path: "/home/ariel/Downloads/outs"